name: NeoKernel Builder

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: for aarch64
      run: sudo apt-get install ccache && mkdir -p ../PLATFORM/prebuilts/gcc/linux-x86/aarch64 && git clone  https://github.com/djb77/aarch64-linux-android-4.9 ../PLATFORM/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9
    - name: make kernel
      run: ./build_kernel.sh
      
    - name: Mod kernel
      run: |   
        ./build/unpackimg.sh ./build/boot.img
        cp -R ./out/arch/arm64/boot/Image.gz-dtb ./build/split_img/
        rm -rf ./build/split_img/boot.img-zImage
        mv ./build/split_img/Image.gz-dtb ./build/split_img/boot.img-zImage
        ./build/repackimg.sh
        mv ./build/image-new.img build/zip/boot.img
        cd build
        cd zip
        zip -r -q -y kernel.zip data META-INF boot.img
      
    - uses: actions/upload-artifact@v2
      with:
        name: kernel.zip
        path: build/zip/
